Repository AICoE/content-pipeline, pull requests merged in 2021-09, with the labels that each got.

#8 Created conference issue template
  .github/ISSUE_TEMPLATE/conference.md
Labels: lgtm, size/S

#9 set up thoth configs for repo
  .aicoe-ci.yaml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/new-tweet.md
  .pre-commit-config.yaml
  .prow.yaml
  manifests/.sops.yaml
  yamllint-config.yaml
Labels: size/M, lgtm

#14 update OWNERS
  OWNERS
Labels: size/XS
